apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-web
  namespace: web
spec:
  provider: azure
  secretObjects:
    - secretName: kv-secrets-web
      type: Opaque
      data:
        - objectName: APPLICATIONINSIGHTS-CONNECTION-STRING # References dbUsername below
          key: APPLICATIONINSIGHTS-CONNECTION-STRING # Key within k8s secret for this value
        - objectName: APPINSIGHTS-INSTRUMENTATIONKEY
          key: APPINSIGHTS-INSTRUMENTATIONKEY
  parameters:
    keyvaultName: "mabr-tiny-java3t-aks-kv"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "04e13382-7a9d-4f32-8f6e-17eedae4ea94"
    objects:  |
      array:
        - |
          objectName: APPLICATIONINSIGHTS-CONNECTION-STRING
          objectAlias: APPLICATIONINSIGHTS-CONNECTION-STRING
          objectType: secret
        - |
          objectName: APPINSIGHTS-INSTRUMENTATIONKEY
          objectAlias: APPINSIGHTS-INSTRUMENTATIONKEY
          objectType: secret
    tenantId: "30adb879-45b4-49c3-bf8b-7731fcce5394"