apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-api
  namespace: api
spec:
  provider: azure
  secretObjects:
  - secretName: kv-secrets-api
    type: Opaque
    data:
      - objectName: SPRING-DATASOURCE-URL
        key: SPRING-DATASOURCE-URL
      - objectName: SPRING-DATASOURCE-USERNAME
        key: SPRING-DATASOURCE-USERNAME
      - objectName: SPRING-DATASOURCE-PASSWORD
        key: SPRING-DATASOURCE-PASSWORD
      - objectName: APPLICATIONINSIGHTS-CONNECTION-STRING
        key: APPLICATIONINSIGHTS-CONNECTION-STRING
      - objectName: APPINSIGHTS-INSTRUMENTATIONKEY
        key: APPINSIGHTS-INSTRUMENTATIONKEY
  parameters:
    keyvaultName: "mabr-tiny-java3t-aks-kv"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "04e13382-7a9d-4f32-8f6e-17eedae4ea94"
    objects:  |
      array:
        - |
          objectName: SPRING-DATASOURCE-URL
          objectAlias: SPRING-DATASOURCE-URL
          objectType: secret
        - |
          objectName: SPRING-DATASOURCE-USERNAME
          objectAlias: SPRING-DATASOURCE-USERNAME
          objectType: secret
        - |
          objectName: SPRING-DATASOURCE-PASSWORD
          objectAlias: SPRING-DATASOURCE-PASSWORD
          objectType: secret
        - |
          objectName: APPLICATIONINSIGHTS-CONNECTION-STRING
          objectAlias: APPLICATIONINSIGHTS-CONNECTION-STRING
          objectType: secret
        - |
          objectName: APPINSIGHTS-INSTRUMENTATIONKEY
          objectAlias: APPINSIGHTS-INSTRUMENTATIONKEY
          objectType: secret
    tenantId: "30adb879-45b4-49c3-bf8b-7731fcce5394"