spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    jdbc-url: ${SPRING_DATASOURCE_URL}?sslmode=verify-full&sslrootcert=DigiCertGlobalRootCA.crt.pem
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SPRING_DATASOURCE_SHOW_SQL}
    hibernate:
      ddl-auto: validate
app.demo.todoapi.load-demo-data: true
app.demo.todoapi.app-client-id: ${APP_CLIENT_ID}
logging.level: warn
logging.level.app.demo.todoapi: debug

