spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    open-in-view: false
server:
  port: ${PORT}
management:
  defaults:
    metrics:
      export:
        enabled: true
  endpoints:
    enabled-by-default: false #new
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
  info:
    git:
      enabled: false
  health:
    probes:
      enabled: true
      add-additional-paths: true

