spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    open-in-view: false
server:
  port: ${PORT}
management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true
# management.health.diskspace.enabled: true
# management.health.database.enabled: true
