spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    jdbc-url: ${SPRING_DATASOURCE_URL}?sslmode=verify-full&sslrootcert=DigiCertGlobalRootCA.crt.pem
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SPRING_DATASOURCE_SHOW_SQL}
    hibernate:
      ddl-auto: validate
app.demoweb.todoweb.load-demo-data: true
logging.level: warn
logging.level.app.demo.todoweb: debug
