spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}?sslmode=verify-full&sslrootcert=DigiCertGlobalRootCA.crt.pem
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SPRING_DATASOURCE_SHOW_SQL}
    hibernate:
      ddl-auto: validate
app.demo.todoweb.load-demo-data: false
logging.level: warn
logging.level.app.demo.todoweb: warn
azure.application-insights.instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY}
azure.application-insights.connection-string:  ${APPLICATIONINSIGHTS_CONNECTION_STRING}