name: cicd-spring-apps-web

on:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - 'todoweb/**'  
  workflow_dispatch:
    inputs:
    
jobs:     

  build_web_app:
    runs-on: ubuntu-latest
    environment: SPRING-APPS
    defaults:
      run:
        working-directory: ./todoweb
    outputs:
      RELEASE_VERSION: ${{ steps.version.outputs.RELEASE_VERSION }}
      RELEASE_NAME: ${{ steps.version.outputs.RELEASE_NAME }}
      RELEASE_FILE_NAME: ${{ steps.version.outputs.RELEASE_FILE_NAME }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
      
      - name: Build the .jar
        run: |
          ./mvnw clean package -DskipTests
      
      # Review: Implement some more mature mono repo versioning 
      - name: Figure out the version info
        id: version
        run: |
          cd ./target
          files=(todoweb*.jar)
          mv "$files" "./todoweb-${GITHUB_SHA}.jar"
          ls -la
          cd ..
          echo "::set-output name=RELEASE_VERSION::${GITHUB_SHA}"
          echo "::set-output name=RELEASE_NAME::todoweb-${GITHUB_SHA}"
          echo "::set-output name=RELEASE_FILE_NAME::todoweb-${GITHUB_SHA}.jar"
          
      - name: Display next version
        run: |
          echo "Version: ${{ steps.version.outputs.RELEASE_VERSION }}"
          echo "Release name: ${{ steps.version.outputs.RELEASE_NAME }}"
          echo "Release file name: ${{ steps.version.outputs.RELEASE_FILE_NAME }}"
      
      - name: 'Upload build artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.version.outputs.RELEASE_NAME }}
          path: ./todoweb/target/${{ steps.version.outputs.RELEASE_FILE_NAME }}
          if-no-files-found: error
          retention-days: 1
  
  deploy_web_app:
    needs: [build_web_app]
    runs-on: ubuntu-latest
    environment: SPRING-APPS
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v2
        with:
          name: ${{needs.build_web_app.outputs.RELEASE_NAME}}
      - name: Check downloaded files
        run: |
          pwd
          ls -la
          ls -la ./${{needs.build_web_app.outputs.RELEASE_FILE_NAME}}
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        #see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux
        #    az account list-locations -o table

      - name: Set default Azure subscription
        run: az account set -s ${{secrets.AZURE_SUBSCRIPTION_ID}}
      
      - name: Deploy to Spring Apps
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az spring app deploy -g ${{secrets.AZURE_RESOURCE_GROUP}} -s ${{secrets.AZURE_SPRING_SERVICE_NAME}} -n ${{secrets.AZURE_WEB_APP_NAME}} --runtime-version Java_11 -d default --artifact-path ./${{needs.build_web_app.outputs.RELEASE_FILE_NAME}} --disable-probe --verbose 

      - name: Run integration test(s)
        run: |
          echo "Run integration tests...."
  
