name: cleanup

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '31 20 * * 5'    
  workflow_dispatch:
    inputs:
      run_cleanup_log_analytics:
        type: boolean
        description: DELETE LOG ANALYTICS WORKSPACE TOO

jobs:
  cleanup-runner:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dispatch clean-up jobs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          environmentsJson=`curl -L -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/martinabrle/tiny-java3t/environments`
          
          echo "environmentsJSON:"
          echo $environmentsJson
          echo "-----------------"
          echo " "

          environmentsJsonArray=`echo $environmentsJson | jq --compact-output '[.environments[].name]'`
          echo "environmentsJSONArray:"
          echo $environmentsJsonArray
          echo "----------------------"
          echo " "

          #remove both leading and trailing whitespaces
          environmentsList=`echo $environmentsJsonArray | sed $'s/^[ \t]*//;s/[ \t]*$//'`
          #remove square brackets
          environmentsList=`echo $environmentsList | sed $'s/[][]//g'`
          #remove both leading and trailing whitespaces
          environmentsList=`echo $environmentsList | sed $'s/^[ \t]*//;s/[ \t]*$//'`
          #replace comma with a new line
          environmentsList=`echo $environmentsList | sed $'s/,/\\\n/g'`
          #remove quotes
          environmentsList=`echo $environmentsList | sed $'s/\"//g'`
          
          echo "Environment list:"
          echo $environmentsList
          echo "-----------------"
          echo " "

          environmentsArray=($environmentsList)
          echo "Environment array: ${environmentsArray[@]}"

          for i in "${environmentsArray[@]}"
          do
            echo "Environment: $i"
            if [[ ! -z $i ]]; then
              gh workflow run cleanup-environment.yml -f environment_input=$i
            fi
          done
